# Generated by Django 5.0.3 on 2024-04-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
