# Generated by Django 5.0.3 on 2024-04-11 11:03

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_membership_end_date_membership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='member',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 4, 11)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 4, 11)),
            preserve_default=False,
        ),
    ]
